# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJBgTtISxSned96eBeJCrKdCP8ngGfsp
"""

# app/anomalies.py
import json
import os
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from sqlalchemy import select, func
from app.db_models import EventRecord, POSTransaction
_NON_PRODUCT_ZONES = {"BILLING", "CHECKOUT_QUEUE", "ENTRY_THRESHOLD"}
def _zones_from_layout() -> list:
layout_path = os.getenv("LAYOUT_PATH", "data/store_layout.json")
if not os.path.exists(layout_path):
return []
try:
with open(layout_path, "r") as f:
layout = json.load(f)
return [z["zone_id"] for z in layout.get("zones", [])]
except Exception:
return []
def get_store_anomalies(store_id: str, db: Session) -> dict:
now = datetime.utcnow()
ten_min_ago = now - timedelta(minutes=10)
thirty_min_ago = now - timedelta(minutes=30)
sixty_min_ago = now - timedelta(minutes=60)
anomalies = []
# 1. BILLING_QUEUE_SPIKE
max_q = db.execute(
select(func.max(EventRecord.queue_depth)).where(
EventRecord.store_id == store_id,
EventRecord.event_type == "BILLING_QUEUE_JOIN",
EventRecord.timestamp >= ten_min_ago,
)
).scalar()
if max_q and max_q > 5:
anomalies.append({
"anomaly_type": "BILLING_QUEUE_SPIKE",
"severity": "CRITICAL",
"detected_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
"suggested_action": "Deploy additional cashier to billing counter immediately.",
"metadata": {"queue_depth": int(max_q)},
})
# 2. DEAD_ZONE — only if store has any recent activity at all
recent_activity = db.execute(
select(func.count(EventRecord.id)).where(
EventRecord.store_id == store_id,
EventRecord.timestamp >= thirty_min_ago,
)
).scalar() or 0
if recent_activity >= 5:
zones = _zones_from_layout() or db.execute(
select(EventRecord.zone_id).where(
EventRecord.zone_id.isnot(None),
EventRecord.store_id == store_id,
).distinct()
).scalars().all()
for zone in zones:
if zone in _NON_PRODUCT_ZONES:
continue
visits = db.execute(
select(func.count(EventRecord.id)).where(
EventRecord.store_id == store_id,
EventRecord.zone_id == zone,
EventRecord.event_type == "ZONE_ENTER",
EventRecord.timestamp >= thirty_min_ago,
)
).scalar() or 0
if visits == 0:
anomalies.append({
"anomaly_type": "DEAD_ZONE",
"severity": "WARN",
"detected_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
"suggested_action": f"Check camera feed for {zone} or investigate physical aisle blockage.",
"metadata": {"zone_id": zone},
})
# 3. CONVERSION_DROP — last 60 min vs 50% baseline
visitors_60m = set(db.execute(
select(EventRecord.visitor_id).where(
EventRecord.store_id == store_id,
)
EventRecord.event_type.in_(["ENTRY", "REENTRY"]),
EventRecord.is_staﬀ == False,
EventRecord.timestamp >= sixty_min_ago,
).scalars().all())
if len(visitors_60m) >= 10:
pos_times = db.execute(
select(POSTransaction.timestamp).where(
POSTransaction.store_id == store_id,
POSTransaction.timestamp >= sixty_min_ago,
)
).scalars().all()
converted = set()
for t in pos_times:
ws = t - timedelta(minutes=5)
v = db.execute(
select(EventRecord.visitor_id).where(
EventRecord.store_id == store_id,
EventRecord.timestamp.between(ws, t),
EventRecord.zone_id.in_(["BILLING", "CHECKOUT_QUEUE"]),
EventRecord.is_staﬀ == False,
)
).scalars().all()
converted.update(v)
cur_rate = len(converted & visitors_60m) / len(visitors_60m)
baseline = 0.50
if cur_rate < baseline * 0.7:
anomalies.append({
"anomaly_type": "CONVERSION_DROP",
"severity": "WARN",
"detected_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
"suggested_action": "Investigate potential inventory stockouts or staﬃng shortages.",
"metadata": {
"current_rate": round(cur_rate, 3),
"baseline_rate": baseline,
},
})
# 4. STALE_FEED per camera
cams = db.execute(
select(EventRecord.camera_id, func.max(EventRecord.ingested_at))
.where(EventRecord.store_id == store_id)
.group_by(EventRecord.camera_id)
).all()
for cam_id, last in cams:
if last and last < ten_min_ago:
anomalies.append({
"anomaly_type": "STALE_FEED",
"severity": "CRITICAL",
"detected_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
"suggested_action": f"Verify camera network connectivity for {cam_id}.",
"metadata": {
"camera_id": cam_id,
"last_event": last.strftime("%Y-%m-%dT%H:%M:%SZ"),
},
})
return {
"store_id": store_id,
"checked_at": now.strftime("%Y-%m-%dT%H:%M:%SZ"),
"anomalies": anomalies,
}