# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJBgTtISxSned96eBeJCrKdCP8ngGfsp
"""

# app/main.py
import json
import os
import time
import traceback
import uuid
from contextlib import asynccontextmanager
from datetime import datetime
from typing import List, Dict, Any, Union
from fastapi import FastAPI, Depends, Request, HTTPException
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.base import BaseHTTPMiddleware
from sqlalchemy import select, func
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import Session
from app.database import init_db, get_db, SessionLocal
from app.db_models import EventRecord
from app.ingestion import ingest_events, load_pos_transactions_from_csv
from app.metrics import get_store_metrics
from app.funnel import get_store_funnel
from app.anomalies import get_store_anomalies
from app.health import get_health
@asynccontextmanager
async def lifespan(app: FastAPI):
init_db()
db = SessionLocal()
try:
finally:
db.close()
yield
csv_path = os.getenv("POS_CSV_PATH", "data/pos_transactions.csv")
n = load_pos_transactions_from_csv(csv_path, db)
print(json.dumps({"event": "startup", "pos_rows_loaded": n}))
app = FastAPI(title="Store Intelligence API", lifespan=lifespan)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])
class LoggingMiddleware(BaseHTTPMiddleware):
async def dispatch(self, request: Request, call_next):
trace_id = uuid.uuid4().hex[:16]
request.state.trace_id = trace_id
start = time.time()
status_code = 500
response = None
try:
response = await call_next(request)
status_code = response.status_code
return response
finally:
latency_ms = round((time.time() - start) * 1000, 2)
store_id = request.path_params.get("store_id")
event_count = getattr(request.state, "event_count", None)
print(json.dumps({
"trace_id": trace_id,
"store_id": store_id,
"endpoint": request.url.path,
"method": request.method,
"latency_ms": latency_ms,
"event_count": event_count,
"status_code": status_code,
"timestamp": datetime.utcnow().isoformat() + "Z",
}))
app.add_middleware(LoggingMiddleware)
@app.exception_handler(HTTPException)
async def http_exc_handler(request: Request, exc: HTTPException):
return JSONResponse(
status_code=exc.status_code,
content={"error": exc.detail, "trace_id": getattr(request.state, "trace_id", "unknown")},
)
@app.exception_handler(RequestValidationError)
async def validation_handler(request: Request, exc: RequestValidationError):
return JSONResponse(
status_code=422,
content={"error": "VALIDATION_ERROR", "details": exc.errors(),
"trace_id": getattr(request.state, "trace_id", "unknown")},
)
@app.exception_handler(OperationalError)
async def db_unavailable_handler(request: Request, exc: OperationalError):
return JSONResponse(
status_code=503,
content={"error": "DATABASE_UNAVAILABLE",
"trace_id": getattr(request.state, "trace_id", "unknown")},
)
@app.exception_handler(Exception)
async def generic_handler(request: Request, exc: Exception):
trace_id = getattr(request.state, "trace_id", "unknown")
print(f"ERROR trace_id={trace_id}\n{traceback.format_exc()}")
return JSONResponse(
status_code=503,
content={"error": "SERVICE_UNAVAILABLE", "trace_id": trace_id},
)
# Accept both bare list and {"events":[...]} wrapper
@app.post("/events/ingest")
def api_ingest_events(
body: Union[List[Dict[str, Any]], Dict[str, Any]],
request: Request,
db: Session = Depends(get_db),
):
if isinstance(body, dict) and "events" in body:
events = body["events"]
elif isinstance(body, list):
events = body
else:
raise HTTPException(status_code=422, detail="Body must be a list or {events: [...]}")
if len(events) > 500:
raise HTTPException(status_code=422, detail="Batch size limit is 500")
if len(events) == 0:
raise HTTPException(status_code=422, detail="Batch is empty")
request.state.event_count = len(events)
return ingest_events(events, db).model_dump()
def _store_exists(db: Session, store_id: str) -> bool:
return db.execute(
select(EventRecord.id).where(EventRecord.store_id == store_id).limit(1)
).first() is not None
@app.get("/stores/{store_id}/metrics")
def api_metrics(store_id: str, db: Session = Depends(get_db)):
if not _store_exists(db, store_id):
raise HTTPException(status_code=404, detail="Store not found or no events ingested")
return get_store_metrics(store_id, db)
@app.get("/stores/{store_id}/funnel")
def api_funnel(store_id: str, db: Session = Depends(get_db)):
if not _store_exists(db, store_id):
raise HTTPException(status_code=404, detail="Store not found")
return get_store_funnel(store_id, db)
@app.get("/stores/{store_id}/heatmap")
def api_heatmap(store_id: str, db: Session = Depends(get_db)):
if not _store_exists(db, store_id):
raise HTTPException(status_code=404, detail="Store not found")
today_start = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)
zone_stats = db.execute(
select(EventRecord.zone_id, func.count(EventRecord.id), func.avg(EventRecord.dwell_ms))
.where(
EventRecord.store_id == store_id,
EventRecord.zone_id.isnot(None),
EventRecord.event_type == "ZONE_DWELL",
EventRecord.is_staﬀ == False,
EventRecord.timestamp >= today_start,
)
).all()
.group_by(EventRecord.zone_id)
total_sessions = db.execute(
select(func.count(func.distinct(EventRecord.visitor_id))).where(
EventRecord.store_id == store_id,
EventRecord.timestamp >= today_start,
EventRecord.is_staﬀ == False,
)
).scalar() or 0
confidence = "LOW" if total_sessions < 20 else "HIGH"
max_dwell = max([float(z[2] or 0) for z in zone_stats], default=1.0) or 1.0
zones_res = []
for z_id, count, avg_dwell in zone_stats:
avg_dwell = float(avg_dwell or 0)
zones_res.append({
"zone_id": z_id,
"visit_frequency": int(count),
"avg_dwell_seconds": round(avg_dwell / 1000.0, 2),
"normalised_score": round((avg_dwell / max_dwell) * 100.0, 2),
"data_confidence": confidence,
})
return {"store_id": store_id, "zones": zones_res}
@app.get("/stores/{store_id}/anomalies")
def api_anomalies(store_id: str, db: Session = Depends(get_db)):
return get_store_anomalies(store_id, db)
@app.get("/health")
def api_health(db: Session = Depends(get_db)):
return get_health(db)
# SSE endpoint for live dashboard
import asyncio
from fastapi.responses import StreamingResponse
@app.get("/stores/{store_id}/stream")
async def event_stream(store_id: str, request: Request):
async def gen():
while True:
if await request.is_disconnected():
break
db = SessionLocal()
try:
payload = {
"metrics": get_store_metrics(store_id, db) if _store_exists(db, store_id) else {},
"funnel": get_store_funnel(store_id, db)["stages"] if _store_exists(db, store_id) else [],
"anomalies": get_store_anomalies(store_id, db)["anomalies"],
"timestamp": datetime.utcnow().isoformat() + "Z",
}
except Exception as e:
payload = {"error": str(e)}
finally:
db.close()
yield f"data: {json.dumps(payload)}\n\n"
await asyncio.sleep(2)
return StreamingResponse(
gen(),
media_type="text/event-stream",
headers={"Cache-Control": "no-cache", "X-Accel-Buﬀering": "no", "Connection": "keep-alive"},
)