# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJBgTtISxSned96eBeJCrKdCP8ngGfsp
"""

# app/models.py
from __future__ import annotations
import re
from datetime import datetime, timezone
from enum import Enum
from typing import Optional, List
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
class EventType(str, Enum):
ENTRY = "ENTRY"
EXIT = "EXIT"
ZONE_ENTER = "ZONE_ENTER"
ZONE_EXIT = "ZONE_EXIT"
ZONE_DWELL = "ZONE_DWELL"
BILLING_QUEUE_JOIN = "BILLING_QUEUE_JOIN"
BILLING_QUEUE_ABANDON = "BILLING_QUEUE_ABANDON"
REENTRY = "REENTRY"
_VISITOR_ID_RE = re.compile(r"^VIS_[A-Za-z0-9]{3,12}$")
class EventMetadata(BaseModel):
model_config = ConfigDict(extra="ignore")
queue_depth: Optional[int] = Field(default=None, ge=0, le=500)
sku_zone: Optional[str] = Field(default=None, max_length=64)
session_seq: int = Field(..., ge=0)
class StoreEvent(BaseModel):
model_config = ConfigDict(extra="ignore", str_strip_whitespace=True)
event_id: str
store_id: str
camera_id: str
visitor_id: str
event_type: EventType
timestamp: str
zone_id: Optional[str] = None
dwell_ms: int = Field(default=0, ge=0)
is_staﬀ: bool
confidence: float = Field(..., ge=0.0, le=1.0)
metadata: EventMetadata
@field_validator("event_id")
@classmethod
def _valid_uuid(cls, v: str) -> str:
try:
UUID(v)
except (ValueError, AttributeError) as e:
raise ValueError(f"event_id must be a valid UUID: {v}") from e
return v
@field_validator("visitor_id")
@classmethod
def _visitor_id_prefix(cls, v: str) -> str:
if not _VISITOR_ID_RE.match(v):
raise ValueError(f"visitor_id must match VIS_<alnum>: {v}")
return v
@field_validator("timestamp")
@classmethod
def _iso8601_utc(cls, v: str) -> str:
try:
parsed = datetime.fromisoformat(v.replace("Z", "+00:00"))
except ValueError as e:
raise ValueError(f"timestamp must be ISO-8601: {v}") from e
if parsed.tzinfo is None:
raise ValueError(f"timestamp must be timezone-aware UTC: {v}")
# canonicalise to ...Z
return parsed.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
@model_validator(mode="after")
def _semantic(self) -> "StoreEvent":
zone_required = {
EventType.ZONE_ENTER, EventType.ZONE_EXIT, EventType.ZONE_DWELL,
EventType.BILLING_QUEUE_JOIN, EventType.BILLING_QUEUE_ABANDON,
}
if self.event_type in zone_required and not self.zone_id:
raise ValueError(f"{self.event_type} requires zone_id")
if self.event_type == EventType.ZONE_DWELL and self.dwell_ms <= 0:
raise ValueError("ZONE_DWELL requires dwell_ms > 0")
if (
self.event_type == EventType.BILLING_QUEUE_JOIN
and self.metadata.queue_depth is None
):
raise ValueError("BILLING_QUEUE_JOIN requires metadata.queue_depth")
return self
class EventBatch(BaseModel):
model_config = ConfigDict(extra="forbid")
events: List[StoreEvent] = Field(..., min_length=1, max_length=500)
class IngestResponse(BaseModel):
accepted_count: int = 0
rejected_count: int = 0
duplicate_count: int = 0
duplicate_ids: List[str] = []
errors: List[str] = []