# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJBgTtISxSned96eBeJCrKdCP8ngGfsp
"""

# app/ingestion.py
import csv
import os
from datetime import datetime, timezone
from typing import List, Dict, Any
from pydantic import ValidationError
from sqlalchemy import insert, select
from sqlalchemy.orm import Session
from app.db_models import EventRecord, POSTransaction
from app.models import StoreEvent, IngestResponse
def _parse_ts(s: str) -> datetime:
return datetime.fromisoformat(s.replace("Z", "+00:00")).astimezone(timezone.utc).replace(tzinfo=None)
def ingest_events(raw_events: List[Dict[str, Any]], db: Session) -> IngestResponse:
valid: List[StoreEvent] = []
errors: List[str] = []
for i, raw in enumerate(raw_events):
try:
valid.append(StoreEvent(**raw))
except ValidationError as e:
errors.append(f"index {i}: {e.errors()[0]['msg']}")
except Exception as e:
errors.append(f"index {i}: {str(e)}")
if not valid:
return IngestResponse(
accepted_count=0,
rejected_count=len(errors),
duplicate_count=0,
duplicate_ids=[],
errors=errors,
)
ids = [e.event_id for e in valid]
existing = set(
db.execute(
).scalars().all()
select(EventRecord.event_id).where(EventRecord.event_id.in_(ids))
)
duplicates = [e.event_id for e in valid if e.event_id in existing]
new_rows = []
now = datetime.utcnow()
for e in valid:
if e.event_id in existing:
continue
new_rows.append({
"event_id": e.event_id,
"store_id": e.store_id,
"camera_id": e.camera_id,
"visitor_id": e.visitor_id,
"event_type": e.event_type.value if hasattr(e.event_type, "value") else str(e.event_type),
"timestamp": _parse_ts(e.timestamp),
"zone_id": e.zone_id,
"dwell_ms": e.dwell_ms,
"is_staﬀ": e.is_staﬀ,
"confidence": e.confidence,
"queue_depth": e.metadata.queue_depth,
"sku_zone": e.metadata.sku_zone,
"session_seq": e.metadata.session_seq,
"ingested_at": now,
})
accepted = 0
if new_rows:
# Use INSERT OR IGNORE to guard against race-condition duplicates
stmt = insert(EventRecord).prefix_with("OR IGNORE")
db.execute(stmt, new_rows)
db.commit()
accepted = len(new_rows)
return IngestResponse(
accepted_count=accepted,
rejected_count=len(errors),
duplicate_count=len(duplicates),
duplicate_ids=duplicates,
errors=errors,
)
def load_pos_transactions_from_csv(csv_path: str, db: Session) -> int:
if not os.path.exists(csv_path):
return 0
inserted = 0
with open(csv_path, "r", encoding="utf-8") as f:
reader = csv.DictReader(f)
for row in reader:
existing = db.execute(
select(POSTransaction.id).where(
POSTransaction.transaction_id == row["transaction_id"]
)
).first()
if existing:
continue
try:
dt = _parse_ts(row["timestamp"])
except Exception:
continue
db.add(POSTransaction(
store_id=row["store_id"],
transaction_id=row["transaction_id"],
timestamp=dt,
basket_value_inr=float(row["basket_value_inr"]),
))
inserted += 1
if inserted:
db.commit()
return inserted