# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJBgTtISxSned96eBeJCrKdCP8ngGfsp
"""

# app/funnel.py
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from sqlalchemy import select, or_
from app.db_models import EventRecord, POSTransaction
def get_store_funnel(store_id: str, db: Session) -> dict:
today_start = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)
# Stage 1: ENTRY or REENTRY — count each visitor_id once
stage_1 = set(db.execute(
select(EventRecord.visitor_id).where(
EventRecord.store_id == store_id,
EventRecord.event_type.in_(["ENTRY", "REENTRY"]),
EventRecord.is_staﬀ == False,
EventRecord.timestamp >= today_start,
)
).scalars().all())
# Stage 2: visited a non-billing zone
if stage_1:
stage_2 = set(db.execute(
select(EventRecord.visitor_id).where(
EventRecord.store_id == store_id,
EventRecord.visitor_id.in_(stage_1),
EventRecord.event_type == "ZONE_ENTER",
~EventRecord.zone_id.in_(["BILLING", "CHECKOUT_QUEUE"]),
EventRecord.timestamp >= today_start,
)
).scalars().all())
else:
stage_2 = set()
# Stage 3: billing queue join or entered BILLING zone
if stage_2:
stage_3 = set(db.execute(
select(EventRecord.visitor_id).where(
EventRecord.store_id == store_id,
EventRecord.visitor_id.in_(stage_2),
or_(
EventRecord.event_type == "BILLING_QUEUE_JOIN",
EventRecord.zone_id == "BILLING",
),
EventRecord.timestamp >= today_start,
)
).scalars().all())
else:
stage_3 = set()
# Stage 4: POS-correlated purchase
stage_4 = set()
if stage_3:
pos_times = db.execute(
select(POSTransaction.timestamp).where(
POSTransaction.store_id == store_id,
POSTransaction.timestamp >= today_start,
)
).scalars().all()
for txn_time in pos_times:
window_start = txn_time - timedelta(minutes=5)
billing_visitors = db.execute(
select(EventRecord.visitor_id).where(
EventRecord.store_id == store_id,
EventRecord.timestamp.between(window_start, txn_time),
EventRecord.zone_id.in_(["BILLING", "CHECKOUT_QUEUE"]),
)
).scalars().all()
for v in billing_visitors:
if v in stage_3:
stage_4.add(v)
c1, c2, c3, c4 = len(stage_1), len(stage_2), len(stage_3), len(stage_4)
def drop(current, nxt):
if current == 0:
return 0.0
return round(((current - nxt) / current) * 100.0, 2)
overall = round((c4 / c1) * 100.0, 2) if c1 > 0 else 0.0
return {
"store_id": store_id,
"as_of": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
"stages": [
{"stage": "ENTRY", "count": c1, "drop_oﬀ_pct": drop(c1, c2)},
{"stage": "ZONE_VISIT", "count": c2, "drop_oﬀ_pct": drop(c2, c3)},
{"stage": "BILLING_QUEUE", "count": c3, "drop_oﬀ_pct": drop(c3, c4)},
{"stage": "PURCHASE", "count": c4, "drop_oﬀ_pct": 0.0},
],
"overall_conversion_pct": overall,
}