# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJBgTtISxSned96eBeJCrKdCP8ngGfsp
"""

# pipeline/demo_generator.py
"""
Demo event generator — produces 200 schema-compliant events for STORE_BLR_002
covering every scoring edge case. Writes to data/events_output.jsonl AND posts
to the API in batches of 50.
# PROMPT: Generate 200 synthetic but realistic store events for STORE_BLR_002 over
# 20 minutes covering: 15 unique visitors, 2 staﬀ, 1 re-entry, 1 group entry of 3,
# realistic zone sequence ENTRY->SKINCARE->HAIRCARE->BILLING->EXIT, 3 billing queue
# events with queue_depth, timestamps starting 2026-03-03T14:00:00Z.
# CHANGES MADE: Added deterministic UUIDs (seeded) so repeated runs produce same
# event_ids exercises idempotency path. Added explicit ZONE_DWELL events at 30s
# intervals to make the heatmap endpoint return data.
"""
import json
import os
import sys
import uuid
import random
import argparse
from datetime import datetime, timedelta, timezone
from pathlib import Path
import httpx
STORE_ID = "STORE_BLR_002"
CAM_ENTRY = "CAM_ENTRY_01"
CAM_FLOOR = "CAM_FLOOR_01"
CAM_BILLING = "CAM_BILLING_01"
BASE_TIME = datetime(2026, 3, 3, 14, 0, 0, tzinfo=timezone.utc)
def fmt_ts(dt: datetime) -> str:
return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
def make_uuid(seed: str) -> str:
"""Deterministic UUID v4 from seed string for idempotency testing."""
rng = random.Random(seed)
bits = rng.getrandbits(128)
# Force version 4
bits = (bits & ~(0xF << 76)) | (0x4 << 76)
bits = (bits & ~(0x3 << 62)) | (0x2 << 62)
return str(uuid.UUID(int=bits))
class EventBuilder:
def __init__(self):
self.events = []
self.seq = {} # visitor_id -> next session_seq
def _next_seq(self, vid: str) -> int:
n = self.seq.get(vid, 0) + 1
self.seq[vid] = n
return n
def add(self, *, visitor_id, event_type, ts, camera_id, zone_id=None,
dwell_ms=0, is_staﬀ=False, confidence=0.92,
queue_depth=None, sku_zone=None):
seq = self._next_seq(visitor_id)
event_id_seed = f"{visitor_id}|{event_type}|{fmt_ts(ts)}|{seq}"
self.events.append({
"event_id": make_uuid(event_id_seed),
"store_id": STORE_ID,
"camera_id": camera_id,
"visitor_id": visitor_id,
"event_type": event_type,
"timestamp": fmt_ts(ts),
"zone_id": zone_id,
"dwell_ms": dwell_ms,
"is_staﬀ": is_staﬀ,
"confidence": confidence,
"metadata": {
"queue_depth": queue_depth,
"sku_zone": sku_zone,
"session_seq": seq,
},
})
def build_visitor_journey(b: EventBuilder, vid: str, start: datetime,
is_staﬀ=False, skip_billing=False):
"""Standard journey: ENTRY -> SKINCARE -> HAIRCARE -> BILLING -> EXIT."""
t = start
b.add(visitor_id=vid, event_type="ENTRY", ts=t, camera_id=CAM_ENTRY, is_staﬀ=is_staﬀ)
t += timedelta(seconds=15)
b.add(visitor_id=vid, event_type="ZONE_ENTER", ts=t, camera_id=CAM_FLOOR,
zone_id="SKINCARE", is_staﬀ=is_staﬀ, sku_zone="MOISTURISER")
t += timedelta(seconds=35)
b.add(visitor_id=vid, event_type="ZONE_DWELL", ts=t, camera_id=CAM_FLOOR,
zone_id="SKINCARE", dwell_ms=35000, is_staﬀ=is_staﬀ, sku_zone="MOISTURISER")
t += timedelta(seconds=10)
b.add(visitor_id=vid, event_type="ZONE_EXIT", ts=t, camera_id=CAM_FLOOR,
zone_id="SKINCARE", dwell_ms=45000, is_staﬀ=is_staﬀ)
t += timedelta(seconds=5)
b.add(visitor_id=vid, event_type="ZONE_ENTER", ts=t, camera_id=CAM_FLOOR,
zone_id="HAIRCARE", is_staﬀ=is_staﬀ, sku_zone="SHAMPOO")
t += timedelta(seconds=40)
b.add(visitor_id=vid, event_type="ZONE_DWELL", ts=t, camera_id=CAM_FLOOR,
zone_id="HAIRCARE", dwell_ms=40000, is_staﬀ=is_staﬀ, sku_zone="SHAMPOO")
t += timedelta(seconds=5)
b.add(visitor_id=vid, event_type="ZONE_EXIT", ts=t, camera_id=CAM_FLOOR,
zone_id="HAIRCARE", dwell_ms=45000, is_staﬀ=is_staﬀ)
if not skip_billing:
t += timedelta(seconds=10)
b.add(visitor_id=vid, event_type="ZONE_ENTER", ts=t, camera_id=CAM_BILLING,
zone_id="BILLING", is_staﬀ=is_staﬀ)
t += timedelta(seconds=60)
b.add(visitor_id=vid, event_type="ZONE_EXIT", ts=t, camera_id=CAM_BILLING,
zone_id="BILLING", dwell_ms=60000, is_staﬀ=is_staﬀ)
t += timedelta(seconds=10)
b.add(visitor_id=vid, event_type="EXIT", ts=t, camera_id=CAM_ENTRY, is_staﬀ=is_staﬀ)
return t
def generate_all() -> list:
b = EventBuilder()
# 15 customer visitors, staggered every 45s
for i in range(1, 16):
vid = f"VIS_{i:06x}"
start = BASE_TIME + timedelta(seconds=i * 45)
build_visitor_journey(b, vid, start, skip_billing=(i in {13, 14}))
# 2 staﬀ members
for j, sid in enumerate(["VIS_aaa001", "VIS_aaa002"]):
start = BASE_TIME + timedelta(minutes=2 + j * 3)
build_visitor_journey(b, sid, start, is_staﬀ=True, skip_billing=True)
# Re-entry: VIS_000003 already has ENTRY+EXIT; add REENTRY 3 minutes after exit
reentry_t = BASE_TIME + timedelta(minutes=10)
b.add(visitor_id="VIS_000003", event_type="REENTRY", ts=reentry_t,
camera_id=CAM_ENTRY, confidence=0.88)
b.add(visitor_id="VIS_000003", event_type="EXIT",
ts=reentry_t + timedelta(seconds=120), camera_id=CAM_ENTRY)
# Group entry: VIS_000007, 000008, 000009 enter within 2 seconds at minute 15
grp_t = BASE_TIME + timedelta(minutes=15)
for k, gv in enumerate(["VIS_g00007", "VIS_g00008", "VIS_g00009"]):
b.add(visitor_id=gv, event_type="ENTRY",
ts=grp_t + timedelta(seconds=k), camera_id=CAM_ENTRY, confidence=0.85)
# 3 billing queue join events with increasing queue_depth
queue_t = BASE_TIME + timedelta(minutes=17)
for k, qd in enumerate([2, 4, 8]):
b.add(
visitor_id=f"VIS_q0000{k+1}"
,
event_type="BILLING_QUEUE_JOIN",
ts=queue_t + timedelta(seconds=k * 30),
camera_id=CAM_BILLING,
zone_id="CHECKOUT_QUEUE",
queue_depth=qd,
)
# Pad with a few extra ZONE_DWELL events to reach ~200
while len(b.events) < 200:
vid = f"VIS_{len(b.events):06x}"
t = BASE_TIME + timedelta(minutes=18, seconds=(len(b.events) % 60))
b.add(visitor_id=vid, event_type="ZONE_DWELL", ts=t, camera_id=CAM_FLOOR,
zone_id="FRAGRANCE", dwell_ms=30000, sku_zone="PERFUME")
return b.events
def write_jsonl(events: list, path: str) -> None:
Path(os.path.dirname(path) or ".").mkdir(parents=True, exist_ok=True)
with open(path, "w") as f:
for ev in events:
f.write(json.dumps(ev) + "\n")
def post_to_api(events: list, api_url: str, batch_size: int = 50) -> dict:
summary = {"posted": 0, "accepted": 0, "duplicates": 0, "errors": []}
with httpx.Client(timeout=10.0) as client:
for i in range(0, len(events), batch_size):
chunk = events[i:i + batch_size]
try:
r = client.post(f"{api_url}/events/ingest", json=chunk)
r.raise_for_status()
body = r.json()
summary["posted"] += len(chunk)
summary["accepted"] += body.get("accepted_count", 0)
summary["duplicates"] += body.get("duplicate_count", 0)
except Exception as e:
summary["errors"].append(f"batch {i}: {e}")
return summary
def main():
ap = argparse.ArgumentParser()
ap.add_argument("--api-url", default=os.getenv("API_URL", "http://localhost:8000"))
ap.add_argument("--output", default="data/events_output.jsonl")
ap.add_argument("--no-post", action="store_true",
help="Only write JSONL, do not POST to API")
args = ap.parse_args()
events = generate_all()
write_jsonl(events, args.output)
print(f"Wrote {len(events)} events to {args.output}")
if args.no_post:
return 0
print(f"Posting to {args.api_url} ...")
summary = post_to_api(events, args.api_url)
print(json.dumps(summary, indent=2))
if summary["errors"]:
print("WARNING: some batches failed", file=sys.stderr)
return 1
return 0
if __name__ == "__main__":
sys.exit(main())