# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJBgTtISxSned96eBeJCrKdCP8ngGfsp
"""

# pipeline/run_full_pipeline.py
"""
End-to-end pipeline runner.
- If data/videos/ contains .mp4 files: runs real CV pipeline (calls run.sh)
- Else: runs demo_generator.py to produce synthetic events
- Verifies all API endpoints respond
- Prints a final summary report
"""
import os
import sys
import json
import subprocess
import time
from pathlib import Path
import httpx
API_URL = os.getenv("API_URL", "http://localhost:8000")
STORE_ID = os.getenv("STORE_ID", "STORE_BLR_002")
VIDEO_DIR = Path(os.getenv("VIDEO_DIR", "data/videos"))
def wait_for_api(timeout: int = 60) -> bool:
print(f"Waiting for API at {API_URL} ...")
deadline = time.time() + timeout
while time.time() < deadline:
try:
r = httpx.get(f"{API_URL}/health", timeout=2.0)
if r.status_code == 200:
print(" API is up.")
return True
except Exception:
pass
time.sleep(2)
print(" API did not respond in time.", file=sys.stderr)
return False
def has_real_videos() -> bool:
if not VIDEO_DIR.exists():
return False
return any(VIDEO_DIR.rglob("*.mp4"))
def run_real_pipeline() -> int:
script = Path(__file__).parent / "run.sh"
print(f"Running real CV pipeline via {script} ...")
return subprocess.call(["bash", str(script)], env={**os.environ, "API_URL": API_URL})
def run_demo_pipeline() -> int:
print("No real videos found — running synthetic demo generator.")
from pipeline import demo_generator
sys.argv = ["demo_generator.py", "--api-url", API_URL]
return demo_generator.main()
def verify_endpoints() -> dict:
results = {}
endpoints = [
("/health", None),
(f"/stores/{STORE_ID}/metrics", None),
(f"/stores/{STORE_ID}/funnel", None),
(f"/stores/{STORE_ID}/heatmap", None),
(f"/stores/{STORE_ID}/anomalies", None),
]
with httpx.Client(timeout=5.0) as c:
for ep, _ in endpoints:
try:
r = c.get(f"{API_URL}{ep}")
results[ep] = {"status": r.status_code, "ok": r.status_code < 400}
except Exception as e:
results[ep] = {"status": None, "ok": False, "error": str(e)}
return results
def main() -> int:
if not wait_for_api():
return 2
if has_real_videos():
rc = run_real_pipeline()
else:
rc = run_demo_pipeline()
if rc != 0:
print(f"Pipeline returned non-zero ({rc})", file=sys.stderr)
print("\nVerifying API endpoints ...")
results = verify_endpoints()
print(json.dumps(results, indent=2))
all_ok = all(r.get("ok") for r in results.values())
print("\n" + ("ALL ENDPOINTS HEALTHY ✓
return 0 if all_ok else 1
" if all_ok else "SOME ENDPOINTS FAILED ✗
"))
if __name__ == "__main__":
sys.exit(main())