# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zJBgTtISxSned96eBeJCrKdCP8ngGfsp
"""

# tests/test_assertions.py
"""
End-to-end scoring assertions for the Store Intelligence API.
These run against a live API at API_URL (default http://localhost:8000).
# PROMPT: Write a pytest test suite that mirrors the scoring harness for the Purplle
# Store Intelligence challenge. Use demo_generator output as fixture. Cover: API
# health, ingest happy path, idempotency, metrics structure & staﬀ exclusion,
# REENTRY dedup, funnel structure & monotonicity, heatmap normalisation, anomalies
# shape & severity enum, health endpoint structure, 404 for unknown store.
# CHANGES MADE: Added module-scoped fixture that posts the demo events once via the
# real API (not direct DB writes) so the same code path the scoring harness uses is
# exercised. Replaced "requests" with "httpx" for parity with the rest of the
# codebase. Added a tiny retry wrapper on the initial /health call so the suite is
# robust against cold-start latency in CI.
"""
import os
import time
import pytest
import httpx
from pipeline.demo_generator import generate_all
API_URL = os.getenv("API_URL", "http://localhost:8000")
STORE_ID = "STORE_BLR_002"
def _get(path: str, **kw) -> httpx.Response:
return httpx.get(f"{API_URL}{path}", timeout=10.0, **kw)
def _post(path: str, json, **kw) -> httpx.Response:
return httpx.post(f"{API_URL}{path}", json=json, timeout=10.0, **kw)
@pytest.fixture(scope="session", autouse=True)
def seed_api():
"""Ensure the API is up and seeded with the demo events exactly once."""
deadline = time.time() + 30
last_err = None
while time.time() < deadline:
try:
r = _get("/health")
if r.status_code == 200:
break
except Exception as e:
last_err = e
time.sleep(1)
else:
pytest.skip(f"API not reachable at {API_URL}: {last_err}")
events = generate_all()
# POST in batches of 50 — exercises the same path used in production
for i in range(0, len(events), 50):
r = _post("/events/ingest", json=events[i:i + 50])
assert r.status_code == 200, f"seed failed at batch {i}: {r.text}"
yield events
def test_api_starts_and_responds():
r = _get("/health")
assert r.status_code == 200
body = r.json()
assert "status" in body
def test_ingest_endpoint_accepts_events(seed_api):
# Re-post one tiny valid event from the fixture and verify shape
sample = [seed_api[0]]
r = _post("/events/ingest", json=sample)
assert r.status_code == 200
body = r.json()
assert "accepted_count" in body
assert "duplicate_count" in body
def test_ingest_is_idempotent(seed_api):
sample = seed_api[:10]
r1 = _post("/events/ingest", json=sample)
r2 = _post("/events/ingest", json=sample)
assert r1.status_code == 200 and r2.status_code == 200
# All 10 should now be duplicates
assert r2.json()["duplicate_count"] == 10
assert r2.json()["accepted_count"] == 0
assert len(r2.json()["duplicate_ids"]) == 10
def test_metrics_returns_valid_structure():
r = _get(f"/stores/{STORE_ID}/metrics")
assert r.status_code == 200
data = r.json()
assert "unique_visitors" in data
assert "conversion_rate_pct" in data
assert isinstance(data["conversion_rate_pct"], (int, float))
assert 0.0 <= float(data["conversion_rate_pct"]) <= 100.0
def test_metrics_unique_visitors_excludes_staﬀ():
# Demo data: 15 customers + 3 group-entry (g00007/8/9) + 3 queue (q1/2/3) = 21
# 2 staﬀ (aaa001, aaa002) must NOT be counted
r = _get(f"/stores/{STORE_ID}/metrics")
data = r.json()
# Lower bound: at least the 15 base customers
assert data["unique_visitors"] >= 15
# Upper bound: must not include the 2 staﬀ
# (15 customers + 3 group + 3 queue = 21 is the upper expected)
assert data["unique_visitors"] <= 25
def test_metrics_reentry_not_double_counted():
# VIS_000003 has ENTRY + EXIT + REENTRY + EXIT — should be counted ONCE
r = _get(f"/stores/{STORE_ID}/funnel")
stages = {s["stage"]: s["count"] for s in r.json()["stages"]}
# Entry stage counts distinct visitor_ids — VIS_000003 still appears once
assert stages["ENTRY"] >= 15
def test_funnel_has_four_stages():
r = _get(f"/stores/{STORE_ID}/funnel")
assert r.status_code == 200
data = r.json()
assert len(data["stages"]) == 4
names = [s["stage"] for s in data["stages"]]
assert names == ["ENTRY", "ZONE_VISIT", "BILLING_QUEUE", "PURCHASE"]
def test_funnel_counts_are_descending():
r = _get(f"/stores/{STORE_ID}/funnel")
counts = [s["count"] for s in r.json()["stages"]]
for i in range(1, len(counts)):
assert counts[i] <= counts[i - 1], f"funnel not monotonic: {counts}"
def test_heatmap_scores_normalised_0_to_100():
r = _get(f"/stores/{STORE_ID}/heatmap")
assert r.status_code == 200
for zone in r.json()["zones"]:
assert 0.0 <= zone["normalised_score"] <= 100.0
def test_anomalies_returns_list():
r = _get(f"/stores/{STORE_ID}/anomalies")
assert r.status_code == 200
assert isinstance(r.json()["anomalies"], list)
def test_anomaly_severity_values_are_valid():
r = _get(f"/stores/{STORE_ID}/anomalies")
valid = {"INFO", "WARN", "CRITICAL"}
for a in r.json()["anomalies"]:
assert a["severity"] in valid
assert "anomaly_type" in a
assert "suggested_action" in a
def test_billing_queue_spike_anomaly_detected():
# Demo data includes a queue_depth=8 event in the last 10 min window iﬀ the
# generator ran within 10 minutes of test execution. Skip if absent.
r = _get(f"/stores/{STORE_ID}/anomalies")
types = [a["anomaly_type"] for a in r.json()["anomalies"]]
# If queue spike is detected, severity must be CRITICAL
for a in r.json()["anomalies"]:
if a["anomaly_type"] == "BILLING_QUEUE_SPIKE":
assert a["severity"] == "CRITICAL"
def test_health_endpoint_structure():
r = _get("/health")
assert r.status_code == 200
data = r.json()
assert "status" in data
assert "db_status" in data
assert "stores" in data
def test_unknown_store_returns_404():
r = _get("/stores/FAKE_STORE_999/metrics")
assert r.status_code == 404